version: "3"
volumes:
  rabbitmq_data:
services:
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.6
    ports:
      - "5601:5601"
